name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.TOKEN_GITHUB  }}
        issue-message: "👋 Hello there! Thank you for opening this issue. We'll get back to you as soon as possible."
        pr-message: "🎉 Welcome! Thank you for your pull request. We'll review it shortly."
